# Get all flights - Without x-api-key - Error Case
GET http://localhost:7000/api/flights
###

# Get all flights - With Invalid Origin - Error Case
GET http://localhost:7000/api/flights?origin=12
x-api-key: 4lyMcCg9V6qNmDSWSo21fTOfLIygHAFglMnLShD236WPt6YyLQ4aLvP7EYWr6DBXoSwc1kfN9RH3CPAAAw1y3Z4TPKiJSDMMOidrKJrdpZGctwTufIUphKxhUzn0LLjm
###

# Get all flights - Success Case
GET http://localhost:7000/api/flights?origin=BOM
x-api-key: 4lyMcCg9V6qNmDSWSo21fTOfLIygHAFglMnLShD236WPt6YyLQ4aLvP7EYWr6DBXoSwc1kfN9RH3CPAAAw1y3Z4TPKiJSDMMOidrKJrdpZGctwTufIUphKxhUzn0LLjm
###

# Create new flight - Error Case
POST http://localhost:7000/api/flights HTTP/1.1
content-type: application/json

{
    "miles": 100,
    "scheduled_departure_time": "2023-02-13T00:00:00.00Z",
    "scheduled_arrival_time": "2023-02-13T04:00:00.00Z",
    "first_class_base_price": 3000.00,
    "economy_class_base_price": 2200.90,
    "num_first_class_seats": 50,
    "num_economy_class_seats": 350
}

###

# Create new flight
POST http://localhost:7000/api/flights HTTP/1.1
content-type: application/json

{
    "name": "IG001",
    "origin": "BOM",
    "destination": "DEL",
    "miles": 100,
    "scheduled_departure_time": "2023-02-13T00:00:00.00Z",
    "scheduled_arrival_time": "2023-02-13T04:00:00.00Z",
    "first_class_base_price": 3000.00,
    "economy_class_base_price": 2200.90,
    "num_first_class_seats": 50,
    "num_economy_class_seats": 350
}

###
# Get flight by id - Error
GET http://localhost:7000/api/flights/abc
###

###
# Get flight by id
GET http://localhost:7000/api/flights/15
###

###
# Update flight by id
PUT http://localhost:7000/api/flights/13 HTTP/1.1
content-type: application/json

{
    "name": "IG001",
    "origin": "BOM",
    "destination": "DEL",
    "miles": 100,
    "scheduled_departure_time": "2023-02-13T00:00:00.00Z",
    "scheduled_arrival_time": "2023-02-13T04:00:00.00Z",
    "first_class_base_price": 3001.00,
    "economy_class_base_price": 2200.90,
    "num_first_class_seats": 50,
    "num_economy_class_seats": 350
}

###
# Delete flight by id
DELETE http://localhost:7000/api/flights/13
###