# Get all flights
GET http://localhost:7000/api/flights
###

# Create new flight
POST http://localhost:7000/api/flights HTTP/1.1
content-type: application/json

{
    "name": "IG001",
    "origin": "BOM",
    "destination": "DEL",
    "miles": 100,
    "scheduled_departure_time": "2023-02-13T00:00:00.00Z",
    "scheduled_arrival_time": "2023-02-13T04:00:00.00Z",
    "first_class_base_price": 3000.00,
    "economy_class_base_price": 2200.90,
    "num_first_class_seats": 50,
    "num_economy_class_seats": 350
}