// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/gin-gonic/gin"
	"github.com/samriddhadev/go-acme-flights/api/controller"
	"github.com/samriddhadev/go-acme-flights/api/router"
	"github.com/samriddhadev/go-acme-flights/config"
	"github.com/samriddhadev/go-acme-flights/repository"
	"github.com/samriddhadev/go-acme-flights/service"
)

// Injectors from wire.go:

func InitializeRouter(cfg *config.Config, ctx *gin.Engine) router.Router {
	acmeFlightRepository := repository.NewAcmeFlightRepository()
	acmeFlightService := service.NewAcmeFlightService(acmeFlightRepository)
	acmeFlightController := controller.NewAcmeFlightController(acmeFlightService)
	routerRouter := router.NewRouter(cfg, ctx, acmeFlightController)
	return routerRouter
}
